Sprint 6 solution
MaxxximL/java-kanban pull request #2
Opened 2024-08-06 11:27 UTC by MaxxximL

Доработана функциональность по техническому заданию спринта

2024-08-07 11:46 UTC, MaxxximL commented
Добрый день!
Не могу понять почему не видно все классы, делаю коммит и пуш из IDE там все внутри. Удалил папку out.
Не проходит одну проверку Java Tests / build / build-task-manager (pull_request) Failing after 13s,
Там ошибка Process finished with exit code -1
Почитал на форуме и изменил в настройках IDE  "debugger.attach.to.process.action", теперь при выполнении Process finished with exit code 0

2024-08-07 20:43 UTC, MaxxximL commented
Из Git Bash прошли все классы

2024-08-08 10:17 UTC, andrew-larkin requested changes
Привет! Структурно все в порядке, но есть баг серьезный - его поправить, дописать тесты и работа будет принята.

2024-08-08 10:17 UTC, andrew-larkin commented on src/service/Main.java
> +
используй данный скрипт для проверки. должно распечататься 13 задач :
TaskManager taskManager = Managers.getDefault();

        for (int i = 1; i < 20; i++) {
            taskManager.createTask(new Task("name" + i, "desc" + i));
        }

        for (int i = 5; i < 18; i++) {
            taskManager.getTaskById(i);
        }

        List<Task> history = taskManager.getHistory();
        System.out.println(history);

2024-08-08 10:17 UTC, andrew-larkin commented on src/service/InMemoryHistoryManager.java
> +        return new ArrayList<>();
у тебя пустая история возвращается таким образом

2024-08-08 10:17 UTC, andrew-larkin commented on test/service/TaskManagerTest.java
> +    }
маловато тестов

2024-08-09 17:16 UTC, MaxxximL commented
Добрый вечер!
Не знаю в каком формате должен выводиться список, получилось 13 таких вот узлов -
( service.InMemoryHistoryManager$Node@16d3586 )
Дописал тесты

2024-08-10 09:38 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-09-21 11:34 UTC, merged